### ISSUE TITLE
TypeError: Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by ivernaloo** [ivernaloo/estate-dashboard#1]
http://scxx.whfcj.gov.cn/scxxbackstage/whfcj/channels/854.html
造成联系解析问题

```javascript
D:\Projects\own\2016\09\property-dashboard\crawler\db\crawler.js:146
                callback([Table[8][0], Table[15][0]])
                                  ^

TypeError: Cannot read property '0' of undefined
    at Request._callback (D:\Projects\own\2016\09\property-dashboard\crawler\db\crawler.js:146:35)
    at Request.self.callback (D:\Projects\own\2016\09\property-dashboard\node_modules\.npminstall\re
quest\2.74.0\request\request.js:187:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (D:\Projects\own\2016\09\property-dashboard\node_modules\.npminstall\requ
est\2.74.0\request\request.js:1044:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (D:\Projects\own\2016\09\property-dashboard\node_modules\.npminst
all\request\2.74.0\request\request.js:965:12)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
[nodemon] app crashed - waiting for file changes before starting...

```

**Comment by ivernaloo** [comment]
```javascript
if(Table.length > 0){
                    callback([Table[8][0], Table[15][0]])
                } else {
                    callback();
                }
```
